import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import c from '../styles/Home.module.scss';

const imgArr = [...Array(100).keys()];

const Home: NextPage = () => {
    const [counter, setCounter] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setCounter(counter + 1);
        }, 1000);
        return () => {
            clearInterval(interval);
        };
    }, [counter]);
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={c.gallery}>
                <h2 className={c.rowName}>Thriller</h2>
                <div className="mobileMultiRow">
                    {imgArr.map((item) => (
                        <a className={c.watchTitle} href="#">
                            <div style={{ backgroundImage: 'url("https://via.placeholder.com/150")' }} />
                        </a>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default Home;
